_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
hotkey:
    value: 5CrB48Not2N5ZDRXzmZHcNWqnT2LgqrHxPe87zkQzmHqXAnv
type:
    value: validator
uid:
    value: 3
version:
    value: 0.0.0
